[Clarity] sBTC Mini peg-in and registry
Trust-Machines/stacks-sbtc pull request #319
Opened 2023-05-03 21:15 UTC by MarvinJanssen

This branch will be used to implement the peg-in and any changes to the registry that are necessary. Currently just some unit tests.

Also adds `@mine-blocks-before` unit test annotation.

2023-05-09 03:06 UTC, MarvinJanssen commented
@FriendsFerdinand I merged your PR #304 into this one so I could start working on some peg-in tests. Still super early and I just generated some basic Bitcoin transactions to have something to work with.

2023-05-15 19:41 UTC, jo-tm commented
@sergey-shandar I think Rust coverage is broken, unrelated to our folder and blocking our merge, let me know if we have to fix it on our side cc/ @MarvinJanssen

2023-05-15 19:43 UTC, xoloki commented
> @sergey-shandar I think Rust coverage is broken, unrelated to our folder and blocking our merge, let me know if we have to fix it on our side cc/ @MarvinJanssen

Oh wow this looks bad: "Unable to locate build via Github Actions API. Please upload with the Codecov repository upload token to resolve issue."

2023-05-16 15:22 UTC, sergey-shandar commented
> @sergey-shandar I think Rust coverage is broken, unrelated to our folder and blocking our merge, let me know if we have to fix it on our side cc/ @MarvinJanssen

I'm investigating the issue.

2023-05-25 19:59 UTC, MarvinJanssen commented
@jo-tm I don't see the comments you mention. Where should I look?

2023-05-30 13:15 UTC, jo-tm commented
looking great, only 1 test is failing:
`./.test/sbtc-peg-in-processor_test.ts => test-peg-in-reveal ... FAILED (173ms)`

2023-05-30 15:53 UTC, MarvinJanssen commented
Yep will discuss it in our upcoming call. Everything is in place, I just messed up calculating the witness Merkle root.

2023-06-04 03:28 UTC, MarvinJanssen commented
I now got a working peg-in reveal test from start to finish! I think this is good to merge, consider it a first version of sBTC peg-in processing and some initial unit tests.

- It verifies that the Bitcoin reveal transaction has been mined with _N_ confirmations and has not been processed before.
- It verifies that the witness script structure is as expected.
- It verifies that the Bitcoin was sent to the peg wallet address of the specified cycle.
- It extracts the destination principal from the witness, and aborts if it is malformed.
- It mints sBTC tokens equal to the pegged-in value.

2023-06-05 15:39 UTC, jo-tm requested changes
reqquested some changes, most important is some FIXME comment.

2023-06-05 15:39 UTC, jo-tm commented on sbtc-mini/contracts/sbtc-controller.clar
> +;; FIXME: Potential issue in that the contract-deployer can mess with the registry state
Can we mitigate this?

2023-06-05 15:39 UTC, jo-tm commented on sbtc-mini/contracts/sbtc-controller.clar
> +;; FIXME: Potential issue in that the contract-deployer can mess with the registry state
I mean before merging.

2023-06-05 23:50 UTC, MarvinJanssen commented on sbtc-mini/contracts/sbtc-peg-in-processor.clar
> +;; (define-read-only (extract-peg-wallet-value (outs (list 8 { value: uint, scriptPubKey: (buff 128) })) (peg-wallet-scriptpubkey (buff 128)))
OK.

2023-06-05 23:55 UTC, MarvinJanssen commented on sbtc-mini/contracts/sbtc-peg-in-processor.clar
> +;; TODO: allow to process multiple reveals at once?
Posted #409.

2023-06-05 23:56 UTC, MarvinJanssen commented on sbtc-mini/contracts/sbtc-testnet-debug-controller.clar
> +;; TODO
OK.

2023-06-06 00:00 UTC, MarvinJanssen commented on sbtc-mini/contracts/sbtc-controller.clar
> +;; FIXME: Potential issue in that the contract-deployer can mess with the registry state
Only if we add a separate launch/bootstrap function to the controller. So the real question is do we want to add a function that will only ever be called once on launch, that is part of the contract forever. (Almost every part of the protocol will call the controller at some point so it'll make the overall read_count dimension of the protocol a bit higher.) Right now I'm "reusing" the upgrade path to do the initial bootstrap.

It is easy to detect if however launches the protocol messes with the state before bootstrapping. Also, it is kind of a moot point because if they want to mess with it then they can just modify the contract source before they deploy.

2023-06-06 00:04 UTC, MarvinJanssen commented on sbtc-mini/tests/sbtc-peg-in-processor_test.clar
> +			;; FIXME: something strange here, can pass any buff in the list and the test will pass.
@FriendsFerdinand curious observation here.

2023-06-06 17:25 UTC, jo-tm commented on sbtc-mini/contracts/sbtc-controller.clar
> +;; FIXME: Potential issue in that the contract-deployer can mess with the registry state
is fine for me if is documented how the initial bootstrap is done

2023-06-06 17:28 UTC, jo-tm requested changes
#TODO maybe can be removed and and issue opened?

2023-06-06 17:28 UTC, jo-tm commented on sbtc-mini/contracts/sbtc-btc-tx-helper.clar
> +;; TODO: Do we need the optional and hard coupling with PoX?
remove TODO and create ticket if necessary.

2023-06-06 17:28 UTC, jo-tm requested changes
#TODO maybe can be removed and and issue opened?

2023-06-06 19:20 UTC, MarvinJanssen commented on sbtc-mini/contracts/sbtc-btc-tx-helper.clar
> +;; TODO: Do we need the optional and hard coupling with PoX?
I would be happy to follow up on it in a future PR, but if you want no TODOs in comments then I can remove it.

2023-06-08 14:36 UTC, jo-tm commented on sbtc-mini/contracts/sbtc-btc-tx-helper.clar
> +;; TODO: Do we need the optional and hard coupling with PoX?
Yes, remove TODOs before merge and open issues if necessary with description.

2023-06-08 14:37 UTC, jo-tm submitted a review, later dismissed

2023-06-08 14:37 UTC, jo-tm commented
We can remove TODOs in the next PR.

2023-06-08 16:55 UTC, MarvinJanssen commented
This is good to go after CI checks pass and the final open comment is addressed. cc @FriendsFerdinand

2023-06-10 19:42 UTC, setzeus commented on sbtc-mini/contracts/sbtc-btc-tx-helper.clar
> +
Might be a dumb question but any reason to not include address versions 0x00 - 0x03? Guessing it's because this contract is specifically sbtc tx help which is always these three?

2023-06-10 19:55 UTC, setzeus commented on sbtc-mini/contracts/sbtc-peg-in-processor.clar
> +		(burn-tx (try! (contract-call? .sbtc-btc-tx-helper was-segwit-tx-mined burn-height tx header tx-index tree-depth wproof witness-merkle-root witness-reserved-data ctx cproof)))
Any reason not to unwrap! & define a specific error message like in (vout-value ...) & (unlock-script ...) a few lines below?

2023-06-10 19:56 UTC, setzeus commented on sbtc-mini/contracts/sbtc-peg-in-processor.clar
>  		(try! (contract-call? .sbtc-registry assert-new-burn-wtxid-and-height burn-wtxid burn-height))
Same comment as above (ie - consistency on unwrap w/ specific issues vs try!)

2023-06-12 02:39 UTC, MarvinJanssen commented on sbtc-mini/contracts/sbtc-btc-tx-helper.clar
> +
Those are legacy address types we cannot use anyway. Technically only `0x06` should be supported but the other ones are/were useful for testing.

2023-06-12 02:41 UTC, MarvinJanssen commented on sbtc-mini/contracts/sbtc-peg-in-processor.clar
> +		(burn-tx (try! (contract-call? .sbtc-btc-tx-helper was-segwit-tx-mined burn-height tx header tx-index tree-depth wproof witness-merkle-root witness-reserved-data ctx cproof)))
To propagate the error raised in `.sbtc-btc-tx-helper`. (So we know that is where the error originated, and what error it is.)

2023-06-12 02:41 UTC, MarvinJanssen commented on sbtc-mini/contracts/sbtc-peg-in-processor.clar
>  		(try! (contract-call? .sbtc-registry assert-new-burn-wtxid-and-height burn-wtxid burn-height))
Same as above, so we know an error originated in the registry and what error it was. (Each contract has its own error space.)

2023-06-12 02:43 UTC, MarvinJanssen commented
@setzeus let me know if my responses are satisfactory. One more approval and we can merge or if you think some changes are needed let me know and I can implement them.

2023-06-12 18:04 UTC, FriendsFerdinand commented on sbtc-mini/contracts/sbtc-btc-tx-helper.clar
> +(define-private (unlock-script-check-length (contract-name-length-byte (optional (buff 1))) (script-length uint))
Maybe I'm not understanding this function correctly, but the `contract-name-length-byte` argument should be 0 or the length, not `none` ever.

2023-06-13 00:38 UTC, setzeus approved these changes
LTGM!

2023-06-13 11:44 UTC, setzeus commented on sbtc-mini/contracts/sbtc-peg-in-processor.clar
> +(define-read-only (is-protocol-caller (who principal))
Random Q / not blocking merge but any particular reason this function has a parameter? Doesn't look like "who" is ever used?

2023-06-13 16:08 UTC, jo-tm commented
@MarvinJanssen this is "This branch is out-of-date with the base branch", will try to merge it myself.

2023-06-13 16:18 UTC, jo-tm commented
@FriendsFerdinand please add a review before the next call, if there nothing blocking we merge or add your changes!

2023-06-13 21:59 UTC, MarvinJanssen commented on sbtc-mini/contracts/sbtc-peg-in-processor.clar
> +(define-read-only (is-protocol-caller (who principal))
You're right I've been removing it on other branches. I should remove it here too.

2023-06-16 02:26 UTC, FriendsFerdinand commented on sbtc-mini/contracts/sbtc-peg-in-processor.clar
> +	(cycle uint)
Don't we want to imply the cycle from the burn-block-height of the transaction?

2023-06-16 02:35 UTC, FriendsFerdinand commented on sbtc-mini/contracts/sbtc-peg-in-processor.clar
> +	(cycle uint)
Don't we want to get the cycle from the burn-height at which the Bitcoin transaction was made. From looking at this, we're allowing the user to peg-in into whatever peg-wallet even if it's not the one they pegged into at that cycle.

2023-06-16 14:47 UTC, FriendsFerdinand commented on sbtc-mini/contracts/sbtc-controller.clar
> +		(is-some (get name (unwrap! (principal-destruct? (get contract entry)) false)))
I was curious if this was the optimal way to determine if it's a standard or contract principal and I got these results: https://gist.github.com/FriendsFerdinand/7c2e4fd6338c258f530d98e7921de526

2023-06-17 13:43 UTC, MarvinJanssen commented on sbtc-mini/contracts/sbtc-controller.clar
> +		(is-some (get name (unwrap! (principal-destruct? (get contract entry)) false)))
That's cool, I didn't give it much thought. Thanks for checking!

2023-06-17 13:51 UTC, MarvinJanssen commented on sbtc-mini/contracts/sbtc-peg-in-processor.clar
> +		(unlock-script (unwrap! (contract-call? .sbtc-btc-tx-helper find-protocol-unlock-witness (unwrap! (element-at? (get witnesses burn-tx) (get n vout-value)) err-missing-witness)) err-unlock-script-no
I guess to do it right we need to track the vout index of the peg-in commitment transaction.

2023-06-17 14:10 UTC, MarvinJanssen commented on sbtc-mini/contracts/sbtc-peg-in-processor.clar
> +	(cycle uint)
It is to make sure that people can still get sBTC for peg-ins that were completed by the signers in previous cycles. Say that your peg-in is completed by the signers near the end of the cycle but you forget to call `complete-peg-in` until the next cycle has started.

It wouldn't allow users to peg into whatever peg wallet they want because the (old) signers wouldn't consume those escrow addresses. And if they do anyway, then the sBTC should materialise, right?

We can base it purely on the burn height but I wonder if there is some edge case that isn't covered if we do it that way.

2023-06-19 22:04 UTC, jo-tm commented on sbtc-mini/contracts/sbtc-peg-in-processor.clar
> +	(cycle uint)
@FriendsFerdinand this works for you?

2023-06-20 01:19 UTC, FriendsFerdinand commented on sbtc-mini/contracts/sbtc-registry.clar
>  		(map-set peg-out-requests nonce {value: value, sender: sender, destination: destination, unlock-script: unlock-script, burn-height: burn-block-height, expiry-burn-height: expiry-burn-height })
I think it's better to preserve the destination as a scriptpubkey rather than this format

2023-06-20 01:24 UTC, FriendsFerdinand commented on sbtc-mini/contracts/sbtc-registry.clar
> +;; TODO: do we want to abstract settled states out
We might want to add an additional state for `being-fulfilled` to be able to add multiple peg-out fulfillements

2023-06-20 01:44 UTC, FriendsFerdinand commented
What does the `p2tr-unlock-script` correspond to? We are registering a request to a specific scriptpubkey. Do we need to know if this scriptpubkey is valid?

2023-06-20 02:53 UTC, FriendsFerdinand approved these changes

2023-06-20 11:25 UTC, MarvinJanssen commented on sbtc-mini/contracts/sbtc-registry.clar
> +;; TODO: do we want to abstract settled states out
Can you elaborate?

2023-06-20 11:27 UTC, MarvinJanssen commented on sbtc-mini/contracts/sbtc-registry.clar
>  		(map-set peg-out-requests nonce {value: value, sender: sender, destination: destination, unlock-script: unlock-script, burn-height: burn-block-height, expiry-burn-height: expiry-burn-height })
Can you explain why? I feel this format is pretty universal and future proof. The format is also used elsewhere in Stacks.

2023-06-20 11:30 UTC, MarvinJanssen commented
@FriendsFerdinand Yes. The design spec requires the protocol become aware of all peg-out requests. However, I would really like to verify that the P2TR funding transactions (commitments) are spendable by ways of the protocol `OP_DROP` format. Otherwise, one could send any Bitcoin transaction that pays to a Taproot address and claim it is a peg-out request.

2023-06-22 00:12 UTC, MarvinJanssen commented on sbtc-mini/contracts/sbtc-peg-in-processor.clar
> +		(unlock-script (unwrap! (contract-call? .sbtc-btc-tx-helper find-protocol-unlock-witness (unwrap! (element-at? (get witnesses burn-tx) (get n vout-value)) err-missing-witness)) err-unlock-script-no
A really simple way can also be to just have the index of the unlocking witness be supplied as a function parameter.

2023-06-22 00:12 UTC, MarvinJanssen commented
@FriendsFerdinand @jo-tm can we merge this since it's already a pretty long PR? The storage format we can address in a future PR because it impacts the entire protocol. The peg-out question is out of scope for this PR and shall be addressed elsewhere.

I think the only open point is on identifying the unlocking witness location.

2023-06-27 09:19 UTC, MarvinJanssen commented on sbtc-mini/contracts/sbtc-registry.clar
> +;; TODO: do we want to abstract settled states out
Ah got you. It makes sense on first face but will there ever be a situation where only a partial amount of the Bitcoin is pegged in by the signers? Perhaps due to collateralization limits? When that happens, they will pay back to the same escrow address in lieu of refunding the remainder? I guess we cannot know the refund address unless that script path is revealed.

2023-06-27 23:05 UTC, jo-tm commented
@MarvinJanssen @setzeus Can you resolve the conflicts and we merge?

2023-06-28 06:31 UTC, MarvinJanssen commented
I didn't really understand where all these merge conflicts came from. These squash merges are really becoming an issue.

In any case, this PR was ready last week. I just cannot merge without getting two approvals. I've been asking for them.

2023-06-28 06:33 UTC, MarvinJanssen commented on sbtc-mini/contracts/sbtc-registry.clar
> +;; TODO: do we want to abstract settled states out
Tracked in #492.

2023-06-28 06:35 UTC, MarvinJanssen commented on sbtc-mini/contracts/sbtc-registry.clar
>  		(map-set peg-out-requests nonce {value: value, sender: sender, destination: destination, unlock-script: unlock-script, burn-height: burn-block-height, expiry-burn-height: expiry-burn-height })
Tracked in #493.

2023-06-28 06:38 UTC, MarvinJanssen commented on sbtc-mini/contracts/sbtc-peg-in-processor.clar
> +		(unlock-script (unwrap! (contract-call? .sbtc-btc-tx-helper find-protocol-unlock-witness (unwrap! (element-at? (get witnesses burn-tx) (get n vout-value)) err-missing-witness)) err-unlock-script-no
Tracked in #494.

2023-06-28 06:39 UTC, MarvinJanssen commented on sbtc-mini/contracts/sbtc-peg-in-processor.clar
> +	(cycle uint)
I'll assume silence means yes for now.

2023-06-28 07:01 UTC, jo-tm approved these changes

2023-06-28 16:23 UTC, setzeus approved these changes

2023-06-28 18:42 UTC, merged