Include clariform spread formatting
Trust-Machines/stacks-sbtc pull request #347
Opened 2023-05-15 18:30 UTC by jo-tm

Closes https://github.com/Trust-Machines/core-eng/issues/305

2023-05-24 21:25 UTC, jo-tm commented
@FriendsFerdinand @setzeus please review this if you can

2023-05-25 16:46 UTC, jo-tm commented
@sergey-shandar you can review if you want, my CI Kungfu is not great yet.

2023-05-30 05:52 UTC, MarvinJanssen requested changes

2023-05-30 05:52 UTC, MarvinJanssen commented on sbtc-mini/scripts/test.sh
> +sudo rm -fR contracts-spread
`test.sh` is the only way to properly run our Clarity based unit tests, so by changing the file you are forcing the Docker dependency on everyone. I think it would be better if we make it a separate file or activate the Clariform Docker command by passing a parameter to `test.sh`. What do you think?

The modifications themselves look fine to me!

2023-06-23 16:29 UTC, sergey-shandar commented
@jo-tm why did the coverage drops? Did we rename/move any coverage report files?

2023-06-27 22:32 UTC, merged