sBTC Mini Stacking Pool & Peg-Transfer 1st Drafts
Trust-Machines/stacks-sbtc pull request #377
Opened 2023-05-25 16:02 UTC by setzeus

1st drafts of both Clarity contracts named above. There are still significant unknowns & troublesome testing so there is no meaningful coverage at the moment - the point of this PR is more so a project draft completion & catch-up with the rest of sBTC-mini contracts.

**Stacking Pool**
The stacking pool implements the five-window mechanism laid out in the sBTC Master doc (disburse/register/vote/transfer/penalty) with every core function implemented (though again, without unit tests). 

**Peg Transfer / Handoff**
The peg-transfer / handoff contract contains a single function that verifies the peg-balance has been transferred from the previous threshold-wallet to the current threshold-wallet.

2023-05-30 05:40 UTC, MarvinJanssen reviewed
Nice, lots of progress.

2023-05-30 05:40 UTC, MarvinJanssen commented on sbtc-mini/contracts/sbtc-peg-transfer.clar
> +            (tx-output-7 (default-to {value: u0, scriptPubKey: current-threshold-hashbytes} (element-at tx-outputs u7)))
We can probably optimise this in a future PR.

2023-05-30 05:40 UTC, MarvinJanssen commented on sbtc-mini/contracts/sbtc-peg-transfer.clar
> +                (is-eq current-threshold-hashbytes (get scriptPubKey tx-output-0))
This is not going to work, the hash bytes + version need to be formatted as a scriptPubKey.

2023-05-30 05:40 UTC, MarvinJanssen commented on sbtc-mini/contracts/sbtc-peg-transfer.clar
> +                (< cycle-peg-balance
Should be `<=`.

2023-05-30 05:40 UTC, MarvinJanssen commented on sbtc-mini/contracts/sbtc-peg-transfer.clar
> +                ) err-peg-balance-not-sufficient)
I think this design is a bit brittle. If the signers, for whatever reason, do the hand-off in more than one transaction, then the protocol is stuck. (Forever?)

2023-05-30 05:40 UTC, MarvinJanssen commented on sbtc-mini/contracts/sbtc-registry.clar
> +)
Why is this function necessary when `set-peg-state-exists`?

Also, do you think a `peg-state` variable is necessary? Can it not be derived from the registry state?

2023-05-30 05:40 UTC, MarvinJanssen commented on sbtc-mini/contracts/sbtc-stacking-pool.clar
> +(define-constant pox-burn-address { version: 0x00, hashbytes: 0x0011223344556699001122334455669900112233445566990011223344556699})
Probably want to just use the zero address.

2023-05-30 05:40 UTC, MarvinJanssen commented on sbtc-mini/contracts/sbtc-stacking-pool.clar
> +(define-data-var reward-cycle-len uint u2100)
These can be constants.

2023-05-30 05:40 UTC, MarvinJanssen commented on sbtc-mini/contracts/sbtc-stacking-pool.clar
>  (define-read-only (get-current-cycle-pool)
You'll have to upgrade to pox-3 now. 😁

2023-05-30 05:40 UTC, MarvinJanssen commented on sbtc-mini/contracts/sbtc-stacking-pool.clar
> +        (if (< latest-disbursed-burn-height burn-block-height)
Can refactor the nested ifs to a series of `asserts!`. Also, using constants with 1 byte buffer values will be more runtime efficient than using `string-ascii`.

2023-05-30 05:40 UTC, MarvinJanssen commented on sbtc-mini/contracts/sbtc-stacking-pool.clar
> +                (is-eq previous-threshold-wallet (get scriptPubKey tx-output-0))
Same comment as the hand-off contract, the hash bytes + version needs to be formatted as a scriptPubKey.

2023-05-30 05:40 UTC, MarvinJanssen commented on sbtc-mini/contracts/sbtc-stacking-pool.clar
> +            (current-cycle (contract-call? 'SP000000000000000000002Q6VF78.pox-2 current-pox-reward-cycle))
If the proving takes too long then pox will move to the next reward cycle and the function will fail. I think the function should accept a cycle parameter.

2023-05-30 05:40 UTC, MarvinJanssen commented on sbtc-mini/contracts/sbtc-stacking-pool.clar
>                      (unwrapped-candidate (unwrap! current-candidate-status err-unwrapping-candidate))
Can this large if block be simplified with `default-to`?

2023-05-30 05:40 UTC, MarvinJanssen commented on sbtc-mini/contracts/sbtc-stacking-pool.clar
> +                (if (>= (/ (* new-candidate-votes u100) next-pool-total-stacked) u70)
Perhaps it would be nice to be able to change the threshold in the future? (Via a `is-protocol-caller` guarded setter.) If so, then it would also be prudent to add a bit more precision. cc @jo-tm

2023-05-30 05:40 UTC, MarvinJanssen commented on sbtc-mini/contracts/sbtc-stacking-pool.clar
> +        ;; Assert that pending-wallet-peg-outs is equal to zero
Did you mean "is not equal to zero"?

2023-05-30 05:40 UTC, MarvinJanssen commented on sbtc-mini/contracts/sbtc-stacking-pool.clar
> +        (asserts! (> (contract-call? .sbtc-registry get-pending-wallet-peg-outs) u1) err-unhandled-request)
Did you mean `> u0`?

2023-05-30 05:40 UTC, MarvinJanssen commented on sbtc-mini/contracts/sbtc-stacking-pool.clar
> +        (ok (unwrap! (contract-call? .sbtc-registry penalty-peg-state-change) (err u1)))
Can just end with the contract call. (Instead of `ok` and `unwrap!`.)

2023-05-30 05:40 UTC, MarvinJanssen commented on sbtc-mini/contracts/sbtc-stacking-pool.clar
> +        )
Repetition can be refactored into a private function. (cf. `penalty-unhandled-request`.)

2023-05-30 05:40 UTC, MarvinJanssen commented on sbtc-mini/contracts/sbtc-stacking-pool.clar
> +        (ok (unwrap! (contract-call? .sbtc-registry penalty-peg-state-change) (err u1)))
As above.

2023-05-30 15:40 UTC, setzeus commented on sbtc-mini/contracts/sbtc-peg-transfer.clar
> +            (tx-output-7 (default-to {value: u0, scriptPubKey: current-threshold-hashbytes} (element-at tx-outputs u7)))
Copy. Believe I went with this after seeing that mapping/folding was more inefficient than doing it manually.

2023-05-30 15:43 UTC, MarvinJanssen commented on sbtc-mini/contracts/sbtc-peg-transfer.clar
> +            (tx-output-7 (default-to {value: u0, scriptPubKey: current-threshold-hashbytes} (element-at tx-outputs u7)))
A fold will definitely be more expensive, just wondering if you want to map all outputs this way or sum them. I think the setup is pretty efficient if this is what you want to do.

2023-05-30 15:45 UTC, setzeus commented on sbtc-mini/contracts/sbtc-peg-transfer.clar
> +                (is-eq current-threshold-hashbytes (get scriptPubKey tx-output-0))
Can you clarify? Thought the version was an internal Clarity struct to help with formatting by defining the transaction type & hashbytes was the actual key?

2023-05-30 15:46 UTC, setzeus commented on sbtc-mini/contracts/sbtc-peg-transfer.clar
> +                (< cycle-peg-balance
Thx, fixed.

2023-05-30 15:47 UTC, setzeus commented on sbtc-mini/contracts/sbtc-peg-transfer.clar
> +                ) err-peg-balance-not-sufficient)
In agreement. Most definitely don't think this is the final design but wanted to get a draft up there / caught-up with the rest of the BTC processors.

2023-05-31 01:29 UTC, FriendsFerdinand commented on sbtc-mini/contracts/sbtc-peg-transfer.clar
> +                (is-eq current-threshold-hashbytes (get scriptPubKey tx-output-0))
No, the version is the address type. See how to turn hashbytes into ScriptPubKey (@MarvinJanssen if you can double-check pls):
https://gist.github.com/FriendsFerdinand/5a74aa1f3a3c27408efcbd7419e4007e

2023-05-31 14:04 UTC, FriendsFerdinand commented on sbtc-mini/contracts/sbtc-peg-transfer.clar
> +            (current-pool-unwrapped (unwrap! (contract-call? .sbtc-stacking-pool get-current-cycle-pool) err-current-pool-not-found))
I think we want to use `get-specific-cycle-pool` here because we already have the current-cycle and `get-current-cycle-pool` does the same thing too.

2023-05-31 14:11 UTC, FriendsFerdinand commented on sbtc-mini/contracts/sbtc-peg-transfer.clar
> +            (parsed-tx (unwrap! (contract-call? .clarity-bitcoin parse-tx tx) err-parsing-btc-tx))
Presumably, this transaction is a segwit transaction? In this case, `parse-wtx` has to be used. If the transaction can be either type, then we'll have to use an `if` branch

2023-05-31 14:25 UTC, FriendsFerdinand commented on sbtc-mini/contracts/sbtc-peg-transfer.clar
> +                ) err-peg-balance-not-sufficient)
think, we can just do a lazy eval

2023-05-31 15:15 UTC, FriendsFerdinand commented on sbtc-mini/contracts/sbtc-stacking-pool.clar
>              (next-cycle (contract-call? 'SP000000000000000000002Q6VF78.pox-2 current-pox-reward-cycle))
`next-cycle` and `current-cycle` are the same here.

2023-05-31 15:52 UTC, FriendsFerdinand commented on sbtc-mini/contracts/sbtc-stacking-pool.clar
> +                (< (get value tx-output-0) dust-limit)
I'm unsure as to how this checks that the funds that went to the ts wallet, went to the previous pool signers. Are you assuming that these outputs are like Accounts that are increased and decreased as funds are spent by the address?

2023-05-31 17:30 UTC, setzeus commented on sbtc-mini/contracts/sbtc-registry.clar
> +)
Updated.

2023-05-31 17:48 UTC, setzeus commented on sbtc-mini/contracts/sbtc-stacking-pool.clar
> +(define-constant pox-burn-address { version: 0x00, hashbytes: 0x0011223344556699001122334455669900112233445566990011223344556699})
Updated, ty.

2023-05-31 17:56 UTC, setzeus commented on sbtc-mini/contracts/sbtc-stacking-pool.clar
> +(define-data-var reward-cycle-len uint u2100)
The first one yeap. 

The second I'm not as sure? I suppose that's an open question: do we want pool cycles & POX cycles to _always_ stay in-sync? What does this mean when thrown into a bad-state?

2023-05-31 20:06 UTC, FriendsFerdinand commented on sbtc-mini/contracts/sbtc-stacking-pool.clar
>  (define-public (signer-register (pre-registered-signer principal) (amount-ustx uint) (pox-addr { version: (buff 1), hashbytes: (buff 32)}) (public-key (buff 33)))
`(public-key (buff 33))`

aren't public keys for schnorr signatures 32 bytes?

2023-05-31 21:15 UTC, FriendsFerdinand commented
Here:
https://github.com/Trust-Machines/core-eng/blob/411c05d1042205a3c89098fb8dc903fe9f51199a/sbtc-mini/contracts/sbtc-stacking-pool.clar#L447
You're using `as-max-len?` with 10, but the maximum amount in the map is 100. I'm assuming, this is a mistake

2023-05-31 21:46 UTC, FriendsFerdinand commented on sbtc-mini/contracts/sbtc-stacking-pool.clar
>              (next-pool-signer (unwrap! (map-get? signer {stacker: tx-sender, pool: next-cycle}) err-not-signer))
Will this ever pass? I find the signer is only defined (`map-set signer`) in this function after this line and not anywhere else.

2023-06-05 23:38 UTC, MarvinJanssen commented on sbtc-mini/contracts/sbtc-peg-transfer.clar
> +                (is-eq current-threshold-hashbytes (get scriptPubKey tx-output-0))
@FriendsFerdinand looks correct. I also have a function to turn the version + hash bytes into a scriptPubKey in my PR #319. (Direct link: https://github.com/Trust-Machines/core-eng/blob/2434a7b3031813e3e01b64147c02366c4fcca77f/sbtc-mini/contracts/sbtc-btc-tx-helper.clar#L75-L80.)

Yes, always P2TR but I also support P2WPKH and P2WSH for now because it made testing easier. Simple to slash that in the future. I purposely did not add the logic to the registry to make it more agnostic. If a future format is added then we can upgrade the helper.

2023-06-05 23:38 UTC, MarvinJanssen commented on sbtc-mini/contracts/sbtc-peg-transfer.clar
> +                ) err-peg-balance-not-sufficient)
Yep it's what it do to extract/process data as well.

2023-06-05 23:41 UTC, MarvinJanssen commented on sbtc-mini/contracts/sbtc-stacking-pool.clar
> +(define-data-var reward-cycle-len uint u2100)
I guess you can call `get-pox-info` on the PoX contract to get the cycle length and then store it in a data var. It is pretty much static so calling PoX every time would be a waste of runtime. 

I can't answer your questions though, something to bring up during the next meeting. I assumed sBTC cycles were always in sync with PoX.

2023-06-05 23:43 UTC, MarvinJanssen commented on sbtc-mini/contracts/sbtc-peg-transfer.clar
> +            (parsed-tx (unwrap! (contract-call? .clarity-bitcoin parse-tx tx) err-parsing-btc-tx))
Under normal circumstances it will be a segwit transaction. But I think according to the spec, the hand-off does not _have_ to happen by the signers. Theoretically, anyone could fund the new address with the right amount of Bitcoin and the protocol would recover. (The same applies to peg out, anyone can fulfil them. So if something terrible happens, the signers or someone else can decide to fulfil a request outside of the protocol.)

2023-06-05 23:44 UTC, MarvinJanssen commented on sbtc-mini/contracts/sbtc-stacking-pool.clar
>  (define-public (signer-register (pre-registered-signer principal) (amount-ustx uint) (pox-addr { version: (buff 1), hashbytes: (buff 32)}) (public-key (buff 33)))
That's right.

2023-06-06 00:23 UTC, setzeus commented on sbtc-mini/contracts/sbtc-stacking-pool.clar
>                      (unwrapped-candidate (unwrap! current-candidate-status err-unwrapping-candidate))
I don't believe so since there are two functions that are specific to that branch? Votes-per-cycle & next-cycle both have unique updates based on whether the candidate exists? 

Could refactor to a "match" but unclear on how default-to would fulfill both map-sets.

2023-06-06 00:56 UTC, setzeus commented on sbtc-mini/contracts/sbtc-stacking-pool.clar
> +                (if (>= (/ (* new-candidate-votes u100) next-pool-total-stacked) u70)
Great idea. Did the following:

Updated to 3 digits / divide by 1000, created a threshold-consensus variable, & created an update-threshold-that checks with a read-only (is-protocol-caller ...) similar to yours.

2023-06-06 01:18 UTC, setzeus commented on sbtc-mini/contracts/sbtc-stacking-pool.clar
> +        (ok (unwrap! (contract-call? .sbtc-registry penalty-peg-state-change) (err u1)))
Copy. Refactored four functions into a private helper

2023-06-06 12:55 UTC, setzeus commented on sbtc-mini/contracts/sbtc-stacking-pool.clar
>              (next-pool-signer (unwrap! (map-get? signer {stacker: tx-sender, pool: next-cycle}) err-not-signer))
Great catch. You're right, should be in (signer-register ...) as well.

2023-06-08 16:14 UTC, jo-tm commented on sbtc-mini/contracts/sbtc-peg-transfer.clar
> +            (current-pool-unwrapped (unwrap! (contract-call? .sbtc-stacking-pool get-current-cycle-pool) err-current-pool-not-found))
lets open a issue for this question, if this is not in the MVP critical path.

2023-06-08 16:27 UTC, setzeus commented on sbtc-mini/contracts/sbtc-stacking-pool.clar
> +                (< (get value tx-output-0) dust-limit)
Check inputs were spent or outputs were sent to POX addresses.***

2023-06-09 17:26 UTC, MarvinJanssen commented on sbtc-mini/.DS_Store
You accidentally committed a `.DS_Store` file.

Strange I thought it was listed in `.gitignore`.

2023-06-09 17:26 UTC, MarvinJanssen commented on sbtc-mini/contracts/pox-2.clar
Can we remove PoX-2?

2023-06-09 17:26 UTC, MarvinJanssen commented on sbtc-mini/tests/sbtc-stacking-pool_test.clar
> +	(if (is-eq 0x00 (contract-call? .sbtc-stacking-pool get-current-window))
Safer to use constant instead of `0x00` magic value.

2023-06-09 17:26 UTC, MarvinJanssen commented on sbtc-mini/contracts/sbtc-peg-transfer.clar
> +            (asserts! (is-eq (contract-call? .sbtc-stacking-pool get-current-window) 0x03)  err-not-in-transfer-window)
Best to use constant instead of magic value `0x03`.

2023-06-09 17:26 UTC, MarvinJanssen commented on sbtc-mini/contracts/sbtc-peg-transfer.clar
> +            (current-unwrapped-threshold-pubkey (unwrap! (contract-call? .sbtc-btc-tx-helper hashbytes-to-scriptpubkey current-threshold-wallet) err-threshold-to-scriptpubkey))
What happens if the peg transfer happens too late and we enter the next cycle? I think it is a question we have been having at different parts of the protocol. Let's discuss in the next meeting and create an issue.

2023-06-09 17:26 UTC, MarvinJanssen commented on sbtc-mini/tests/pox-3_test.ts
File can be deleted.

2023-06-10 01:22 UTC, setzeus commented on sbtc-mini/contracts/sbtc-peg-transfer.clar
> +            (asserts! (is-eq (contract-call? .sbtc-stacking-pool get-current-window) 0x03)  err-not-in-transfer-window)
Added same window constants used in stacking-pool

2023-06-10 01:24 UTC, setzeus commented on sbtc-mini/contracts/sbtc-peg-transfer.clar
> +            (current-unwrapped-threshold-pubkey (unwrap! (contract-call? .sbtc-btc-tx-helper hashbytes-to-scriptpubkey current-threshold-wallet) err-threshold-to-scriptpubkey))
Copy. Will draft issue & surface on our T meeting.

2023-06-13 18:04 UTC, setzeus commented on sbtc-mini/contracts/sbtc-stacking-pool.clar
>              (next-cycle (contract-call? 'SP000000000000000000002Q6VF78.pox-2 current-pox-reward-cycle))
Just checked & realized I overlooked this in latest commit so leaving unresolved momentarily.

2023-06-13 18:07 UTC, setzeus commented on sbtc-mini/contracts/sbtc-stacking-pool.clar
> +(define-data-var reward-cycle-len uint u2100)
Realizing this is a difference b/w mini & production, closing for now but will create issue about this.

2023-06-13 18:12 UTC, setzeus commented on sbtc-mini/contracts/sbtc-stacking-pool.clar
>              (next-cycle (contract-call? 'SP000000000000000000002Q6VF78.pox-2 current-pox-reward-cycle))
Fixed

2023-06-16 11:39 UTC, setzeus commented
Querying for approvals, @MarvinJanssen & @FriendsFerdinand - lmk if you guys have any additional comments / changes needed.

@jo-tm & @radicleart feel free to review yourselves too if / when you have the time.

2023-06-20 04:33 UTC, FriendsFerdinand approved these changes

2023-06-20 20:23 UTC, jo-tm commented on sbtc-mini/contracts/sbtc-btc-tx-helper.clar
> +		;; TODO: optimise to one call
let's remove TODOs from main branch and open a new issue.

2023-06-20 20:30 UTC, jo-tm requested changes
small TODO removal and one test is failing (if is not critical just by pass it): `, should return none ... ok (57ms)`

`/.test/sbtc-stacking-pool_test.ts => test-get-current-window: Get current window ... FAILED (101ms)`

2023-06-27 22:59 UTC, jo-tm approved these changes

2023-06-27 23:00 UTC, merged