fix: will fail when a coinbase tx is not confirmed
Trust-Machines/stacks-sbtc pull request #422
Opened 2023-06-09 17:33 UTC by FriendsFerdinand

Issue: `as-segwit-tx-mined-compact` should fail if a coinbase transaction cannot be confirmed to be included in a block.

Fix:  verifying a transaction fails when a transaction verification returns an `(ok false)`.

2023-07-06 10:25 UTC, MarvinJanssen approved these changes
Let's get this merged.

cc @friedger

2023-07-13 11:56 UTC, jo-tm commented
We need 2 reviews from @MarvinJanssen @friedger @setzeus

2023-07-18 11:41 UTC, jo-tm commented
work in progress.

2023-07-19 03:07 UTC, MarvinJanssen commented
@FriendsFerdinand can we bring the generation script to a separate PR? Then we can merge the clarity-bitcoin fix already.

2023-07-19 13:43 UTC, friedger approved these changes
LGTM

The change to bitcoin library looks good.

We can keep the proof generator code as work in progress in the code base.

2023-07-19 13:43 UTC, friedger commented on sbtc-mini/tests/clarity-bitcoin_test.clar
> +      err-res (begin (print { err-res: err-res }) (ok err-res))
Do we expect a particular error here?

2023-07-20 08:52 UTC, friedger commented
Unit tests needs to be fixed @FriendsFerdinand

2023-07-20 08:53 UTC, friedger requested changes
Unit tests fail

2023-07-21 08:23 UTC, MarvinJanssen commented
The tests that are failing are coming from the peg-in processor. I think that merging main will resolve the failing tests.

2023-07-21 21:03 UTC, FriendsFerdinand commented on sbtc-mini/tests/clarity-bitcoin_test.clar
> +      err-res (begin (print { err-res: err-res }) (ok err-res))
Yes, the output is too long to be parsed. Uncommented.

2023-07-24 05:28 UTC, MarvinJanssen commented
@friedger waiting on your approval.

2023-07-24 10:19 UTC, friedger approved these changes
LGTM

2023-07-24 10:19 UTC, merged