More sBTC Registry tests
Trust-Machines/stacks-sbtc pull request #511
Opened 2023-07-06 00:23 UTC by jo-tm

* Cannot set a peg wallet for a cycle that already has one 
* Get peg wallet for cycle with none set returns null
*  Get cycle for peg wallet not set returns null
* Cannot settle a peg-out request that is not pending
* Fail to get a peg-out request that does not exist
* Good increments of peg-out nonce
* peg-out-requests-pending is properly incremented

2023-07-06 02:29 UTC, MarvinJanssen requested changes
Nice! Some minor comments.

2023-07-06 02:29 UTC, MarvinJanssen commented on sbtc-mini/tests/sbtc-registry_test.clar
> +    (let ((req1 (unwrap! (contract-call? .sbtc-registry insert-peg-out-request u1 tx-sender u100 mock-destination mock-unlock-script) (err "insert-peg-out-request should have succeeded"))))
You don't have to nest `let`. They are evaluated left to right and you can use previous variables.

2023-07-06 02:29 UTC, MarvinJanssen commented on sbtc-mini/tests/sbtc-registry_test.clar
> +   (let ((req1 (unwrap! (contract-call? .sbtc-registry insert-peg-out-request u1 tx-sender u100 mock-destination mock-unlock-script)
Same comment as above.

2023-07-06 12:47 UTC, jo-tm commented on sbtc-mini/tests/sbtc-registry_test.clar
> +    (let ((req1 (unwrap! (contract-call? .sbtc-registry insert-peg-out-request u1 tx-sender u100 mock-destination mock-unlock-script) (err "insert-peg-out-request should have succeeded"))))
fixed like this but I still have a problem with the `begin`:

problem:
```javascript
expecting >= 2 arguments, got 1 clarity
(begin expr1 expr2 expr3 ... expr-last) -> A
// Description The begin function evaluates each of its input expressions, returning the return value of the last such expression. Note: intermediary statements returning a response type must be checked.
```

```clarity
(define-public (test-peg-out-request-nonce-increment)
  (begin
    (unwrap! (contract-call? .sbtc-registry insert-peg-out-request u1 tx-sender u100 mock-destination mock-unlock-script) (err "insert-peg-out-request should have succeeded"))
    (let (nonce1 (contract-call? .sbtc-registry get-peg-out-nonce)))
    (unwrap! (contract-call? .sbtc-registry insert-peg-out-request u2 tx-sender u100 mock-destination mock-unlock-script) (err "insert-peg-out-request should have succeeded"))
    (let (nonce2 (contract-call? .sbtc-registry get-peg-out-nonce)))
    (unwrap! (contract-call? .sbtc-registry insert-peg-out-request u3 tx-sender u100 mock-destination mock-unlock-script) (err "insert-peg-out-request should have succeeded"))
    (let (nonce3 (contract-call? .sbtc-registry get-peg-out-nonce)))
	(asserts! (is-eq nonce1 u1) (err "Peg-out request nonce for req1 should be u1"))
	(asserts! (is-eq nonce2 u2) (err "Peg-out request nonce for req2 should be u2"))
	(asserts! (is-eq nonce3 u3) (err "Peg-out request nonce for req3 should be u3"))
	(ok true)
  )
)
```

2023-07-08 07:57 UTC, MarvinJanssen commented on sbtc-mini/tests/sbtc-registry_test.clar
> +    (let ((req1 (unwrap! (contract-call? .sbtc-registry insert-peg-out-request u1 tx-sender u100 mock-destination mock-unlock-script) (err "insert-peg-out-request should have succeeded"))))
Change the first `begin` to a single `let` and then use that.

```clarity
(define-public (test-peg-out-request-nonce-increment)
  (let (
    (initial-nonce (contract-call? .sbtc-registry get-peg-out-nonce))
    (nonce1 (unwrap! (contract-call? .sbtc-registry insert-peg-out-request u1 tx-sender u100 mock-destination mock-unlock-script) (err "insert-peg-out-request should have succeeded")))
    (nonce2 (unwrap! (contract-call? .sbtc-registry insert-peg-out-request u1 tx-sender u100 mock-destination mock-unlock-script) (err "insert-peg-out-request should have succeeded")))
    (nonce3 (unwrap! (contract-call? .sbtc-registry insert-peg-out-request u1 tx-sender u100 mock-destination mock-unlock-script) (err "insert-peg-out-request should have succeeded")))
    )
  (asserts! (is-eq nonce1 (+ initial-nonce u1)) (err "Peg-out request nonce for req1 should be u1"))
  (asserts! (is-eq nonce2 (+ initial-nonce u2)) (err "Peg-out request nonce for req2 should be u2"))
  (asserts! (is-eq nonce3 (+ initial-nonce u3)) (err "Peg-out request nonce for req3 should be u3"))
  (ok true)
  )
)
```

2023-07-13 12:24 UTC, jo-tm commented on sbtc-mini/tests/sbtc-registry_test.clar
> +    (let ((req1 (unwrap! (contract-call? .sbtc-registry insert-peg-out-request u1 tx-sender u100 mock-destination mock-unlock-script) (err "insert-peg-out-request should have succeeded"))))
will try this.

2023-07-18 12:06 UTC, jo-tm commented
WIP: fix the tests.

2023-07-25 06:56 UTC, jo-tm commented
please review again @MarvinJanssen @setzeus

2023-07-25 07:15 UTC, friedger approved these changes
Only nits

2023-07-25 07:15 UTC, friedger commented on sbtc-mini/tests/sbtc-registry_test.clar
> +;; @name Get peg wallet for cycle with none set returns null
nit: returns none

2023-07-25 07:15 UTC, friedger commented on sbtc-mini/tests/sbtc-registry_test.clar
> +(define-public (test-settle-non-pending-peg-out-request)
Reading these tests, it is not clear what the expected result is. The test `test-peg-out-request-nonce-increment` has a nice arrange-act-assert structure.

2023-07-26 16:25 UTC, jo-tm commented on sbtc-mini/tests/sbtc-registry_test.clar
> +(define-public (test-settle-non-pending-peg-out-request)
changed to:

```clarity
;; @name Cannot settle a peg-out request id that is not pending
;; @mine-blocks-before 5
(define-public (test-settle-non-pending-peg-out-request)
  (begin
    (unwrap! (contract-call? .sbtc-registry get-and-settle-pending-peg-out-request u10 peg-out-state-fulfilled) (ok true))
    (err "Should not be settle because req id was not pending")
  )
)
```

2023-07-28 09:56 UTC, MarvinJanssen approved these changes
LGTM

2023-07-28 09:59 UTC, merged