Add state to processed ops and trim the table
Trust-Machines/stacks-sbtc pull request #557
Opened 2023-07-13 23:24 UTC by jferrant

I didn't have internet for a majority of the day, so just spent some time looking over the code and seeing what sort of improved state I could easily add.

This is not entirely necessary, but now it will poll for withdrawals and deposits and save its last processed state. It should help with continually broadcasting sBTC transactions for a half processed transaction if the coordinator crashes. It will be smart enough to pick up where it left off to some extent now. Still not perfect by any means but I think its a worthwhile change. Feel free to suggest improvements on it.

I trim the table of completed transactions, however, I could leave them and add logic to not overwrite completed transactions with new ones if we set the blockheight back in time, but I feel like we would expect these to be forcibly reprocessed if we are setting the blockheight back...so I think trimming the table makes more sense. (The case of the coordinator processing most but not all the transactions at some block height seems unlikely and would be the only scenario I can think of where we would want to go back in time and process some but not all the transactions at a given block height...We currently poll all peg ins and all peg outs before attempting processing so they would all be already stored in the database with status::NEW for a given block height)

2023-07-13 23:25 UTC, jferrant commented on stacks-coordinator/src/bitcoin_wallet.rs
> -        assert_eq!(btc_tx.output[1].value, 10000);
This is an unrelated change to fix tests broken by the last merge. I can pull this out later, but just leaving it here until I get eyes on this PR.

2023-07-13 23:26 UTC, jferrant commented on stacks-coordinator/src/coordinator.rs
> +        loop {
This change I think is a good one to have even if we don't have the added status...before we were polling everything but only processing one sbtc op per poll call...I think we should poll everything, process everything, then poll again, etc.

2023-07-13 23:27 UTC, jferrant commented on stacks-coordinator/src/coordinator.rs
> +            self.peg_queue()
In theory we could crash right before this call when the broadcast function has already gone through, but ....not sure how we could ever prevent that XD

2023-07-14 08:28 UTC, netrome requested changes
It's not obvious to me how the addition of the peg queue status improves anything in terms of processing policy, and I'm afraid the introduction of the new complexity might bring on more bugs.

I recommend holding this change until we know if it's worth spending more time on the coordinator.

2023-07-14 08:28 UTC, netrome commented on stacks-coordinator/src/coordinator.rs
> +        loop {
Yeah that makes sense.

2023-07-14 08:49 UTC, stjepangolemac reviewed
I see this PR as 3 different types of changes:

1. Smaller miscellaneous fixes
2. Batching when processing operations
3. Additional statuses when processing

First type I'd pull out into a separate PR and review / merge quickly, no issues there. 

Second one doesn't make a material difference for the execution so I don't have any strong preferences there. Although, if we want to get closer to a state machine, a single operation / event is closer to the ideal.

When it comes to additional bookkeeping of statuses when processing, I think that's something we need but it's very hard to even write a spec for it. There's a good chance we might introduce additional complexity and bugs without being confident that we've covered all the cases. I think we first need to find out if it's worth to spend more time on the coordinator, and if it is then first become confident about the spec, then the implementation.

2023-07-14 11:45 UTC, jferrant commented
> It's not obvious to me how the addition of the peg queue status improves anything in terms of processing policy, and I'm afraid the introduction of the new complexity might bring on more bugs.
> 
> I recommend holding this change until we know if it's worth spending more time on the coordinator.

The only benefit is if for some reason coordinator crashes after having polled the node and partially finished processing an sBTC op...it will pick up where it left off for that op and not rebroadcast an sBTC transaction if it's already done so

2023-07-14 13:53 UTC, closed without merging