sBTC-mini Stacking Pool Quick Fixes
Trust-Machines/stacks-sbtc pull request #578
Opened 2023-07-17 13:51 UTC by setzeus

Minor/Medium changes to address [562](https://github.com/Trust-Machines/stacks-sbtc/issues/562), [547](https://github.com/Trust-Machines/stacks-sbtc/issues/547), & [548](https://github.com/Trust-Machines/stacks-sbtc/issues/548). 

Main change is the addition of a private helper (mass-delegate-stack-extend ...) that extends stacking to either the burn address (in the form of penalize-helper) or to the newly voted-upon sBTC-wallet (in the form of a consensus vote).

Since the private function runs in different places, the response handling is inconsistent & could probably be "prettier" if any review has a suggestion for line 729.

2023-07-17 17:21 UTC, setzeus commented
@FriendsFerdinand neither of these updates changes the minimal unit tests found in sbtc-stacking-pool_test.clar. We're still working on how to best POX-3 & other contracts testing 2.0 in another branch.

Fixes here are mainly to address the minor/medium issues flagged in linked issues. Minor one from Mike was removing a dummy/test function I left in a WIP. 

The two medium issues flagged by Friedger had to do with me missing "delegate-stack-extend" calls in both voting & penalizing. This PR addresses both of those issues by using a private (mass-delegate-stack-extend ...) found in line 738; this is called from either (vote-for-threshold-wallet-candidate ...) once the next peg-wallet has found voting consensus, or from one of the four (penalize-helper ...) functions once a penalty is successfully submitted.

2023-07-17 17:27 UTC, friedger commented on sbtc-mini/contracts/sbtc-stacking-pool.clar
> +    (try! (match (fold mass-delegate-stack-extend (get stackers penalized-pool) (ok {stacker: tx-sender, unlock-burn-height: u0, pox-addr: pox-burn-address}))
Why not just return the result of the fold call?

2023-07-17 17:29 UTC, jo-tm commented
We are following the Diagram in the Main Doc, STACKING:
![image](https://github.com/Trust-Machines/stacks-sbtc/assets/30682875/4c66ae94-f328-452e-a8cf-727e9746c001)

2023-07-17 17:29 UTC, friedger commented on sbtc-mini/contracts/sbtc-stacking-pool.clar
> +                                (match (as-contract (contract-call? .pox-3 stack-aggregation-commit-indexed pox-addr next-cycle))
`stack-aggregation-commit-indexed` should be called the first time the 70% condition passed, thereafter `stack-aggregation-commit-increase` needs to be called with the index from the first call.

See https://github.com/friedger/clarity-stacking-pools/blob/main/contracts/pox-pool-self-service.clar#L175

2023-07-17 17:29 UTC, jo-tm commented
SBTC MINTING (PEG-IN):
![image](https://github.com/Trust-Machines/stacks-sbtc/assets/30682875/f849af99-4a1c-4c95-996a-5593a1847431)

2023-07-17 18:24 UTC, friedger commented
To be able to handle the penalty we must to not lock the stackers during the voting window.
Instead, we should call the extend with either burn address or peg-wallet during the penalty window.

The penalty window must start before the pox prepare phase. Maybe 200 blocks before the start of the cycle.

2023-07-17 22:47 UTC, setzeus commented on sbtc-mini/contracts/sbtc-stacking-pool.clar
> +                                (match (as-contract (contract-call? .pox-3 stack-aggregation-commit-indexed pox-addr next-cycle))
Thinking through this I don't believe we need `stack-aggregation-commit-increase`?

1. The pool of stackers registered in the previous cycle
2. Whether they vote for the winning wallet, they vote for the losing wallet, or they _abstain_ from the vote, they should still be part of the extend-delegate + aggregate commit with the winning wallet
3. Once the winning wallet reaches consensus (> 70% stacking weight), we don't care for additional votes
4. Only registered signers can vote & that list of registered signers is fixed (aka no one can register & vote in the same cycle)

Therefore once we mass-delegate-extend & aggregate-commit we should never need to aggregate-commit-increase? At least within the voting logic*

2023-07-18 01:17 UTC, setzeus commented on sbtc-mini/contracts/sbtc-stacking-pool.clar
> +    (let
Didn't get picked up but took care of this [in latest commit](https://github.com/Trust-Machines/stacks-sbtc/pull/578/commits/0df2d20e75f3e8c9d350ec981b4ae9ad4f9f7a9c) with a simple asserts: 

;; Assert previous pox-return was (ok ...)
`(asserts! (is-ok pox-return) err-mass-delegate-stack-extend)`

2023-07-18 01:18 UTC, setzeus commented on sbtc-mini/contracts/sbtc-stacking-pool.clar
> +    (try! (match (fold mass-delegate-stack-extend (get stackers penalized-pool) (ok {stacker: tx-sender, unlock-burn-height: u0, pox-addr: pox-burn-address}))
Severely overcomplicated myself, appreciate the suggestion.

2023-07-18 16:51 UTC, friedger commented on sbtc-mini/contracts/sbtc-stacking-pool.clar
> +                                (match (as-contract (contract-call? .pox-3 stack-aggregation-commit-indexed pox-addr next-cycle))
Ok, make sense. If voting is not required for signers.

2023-07-18 21:56 UTC, friedger commented
Blocked by https://github.com/Trust-Machines/stacks-sbtc/issues/582

2023-07-19 03:27 UTC, MarvinJanssen requested changes
Looks good, comments are mostly readability questions.

2023-07-19 03:27 UTC, MarvinJanssen commented on sbtc-mini/contracts/sbtc-stacking-pool.clar
> +(define-constant err-wallet-consensus-reached-execution (err u39))
Just an FYI for everyone. We need to formally lay down all protocol error codes. I will bring it up the next meeting.

2023-07-19 03:27 UTC, MarvinJanssen commented on sbtc-mini/contracts/sbtc-stacking-pool.clar
>          (if (is-none current-candidate-status)
This entire function is pretty big with a lot of nesting. Is it possible to split it up into a few functions for readability?

2023-07-19 03:27 UTC, MarvinJanssen commented on sbtc-mini/contracts/sbtc-stacking-pool.clar
> +                    true
This nested structure is pretty hard to follow. (Especially the many else/match err branches.) Can it be refactored to a series of `asserts!`?

2023-07-19 12:53 UTC, setzeus commented on sbtc-mini/contracts/sbtc-stacking-pool.clar
>          (if (is-none current-candidate-status)
Refactored with series of asserts, more in line with what you were thinking?

2023-07-19 12:53 UTC, setzeus commented on sbtc-mini/contracts/sbtc-stacking-pool.clar
> +                    true
Yeap, updated whenever you get a chance to approve.

2023-07-19 13:38 UTC, friedger reviewed
Use of unwrap-panic is not clear to me.

2023-07-19 13:38 UTC, friedger commented on sbtc-mini/contracts/sbtc-stacking-pool.clar
> +                    (unwrapped-candidate (unwrap-panic current-candidate-status))
current-candiate-status is-none, isn't it?
As checked here: https://github.com/Trust-Machines/stacks-sbtc/pull/578/files#diff-9e54e6dfb041bc4c76781bc43adfdf0ce7f1b980d41f9207780022f52d558cf8R487

2023-07-19 13:38 UTC, friedger commented on sbtc-mini/contracts/sbtc-stacking-pool.clar
> +                                    {last-aggregation: (some block-height), reward-index: (some (unwrap-panic (as-contract (contract-call? .pox-3 stack-aggregation-commit-indexed pox-addr next-cycle)
I would put the result of the contract call into a separate line/variable.
unwrap-panic seems wrong as stack-aggregation-commit can return an error.

2023-07-20 03:11 UTC, setzeus commented on sbtc-mini/contracts/sbtc-stacking-pool.clar
> +                    (unwrapped-candidate (unwrap-panic current-candidate-status))
Negative, I think? The (let ...) runs when one of the (and ...) conditions fail. I check (is-none current-candidate=status) is true as the first condition.

If that returns as false, aka current-candidate-status *does exist* then that triggers the (let ...) branch. Since we know current-candidate-status is a (some ...) we can safely unwrap-panic.

2023-07-20 03:12 UTC, setzeus commented on sbtc-mini/contracts/sbtc-stacking-pool.clar
> +                    {threshold-wallet-candidates: (unwrap-panic (as-max-len? (append (get threshold-wallet-candidates next-pool) pox-addr) u100))}
Copy. Changing back. I think I'm now swinging the other way on using unwrap-panic instead of overusing (unwrap! ...). 

Any chance you could summarize the conditions on when you find it appropriate to specifically unwrap-panic?

2023-07-20 03:20 UTC, setzeus commented on sbtc-mini/contracts/sbtc-stacking-pool.clar
> +                                    {last-aggregation: (some block-height), reward-index: (some (unwrap-panic (as-contract (contract-call? .pox-3 stack-aggregation-commit-indexed pox-addr next-cycle)
Changed back to a match, will only use panic sparingly / as we define.

2023-07-20 06:05 UTC, friedger commented on sbtc-mini/contracts/sbtc-stacking-pool.clar
> +                    {threshold-wallet-candidates: (unwrap-panic (as-max-len? (append (get threshold-wallet-candidates next-pool) pox-addr) u100))}
I would use unwrap-panic only when I am sure that panic won't happen.

2023-07-20 06:06 UTC, friedger commented on sbtc-mini/contracts/sbtc-stacking-pool.clar
> +                    (unwrapped-candidate (unwrap-panic current-candidate-status))
OK, the git diff was not clear to me.

2023-07-20 09:24 UTC, friedger requested changes
Needs rebase.

I have an issue with the control flow of signer-pre-register

2023-07-20 09:24 UTC, friedger commented on sbtc-mini/contracts/sbtc-stacking-pool.clar
> +(define-constant err-wallet-consensus-reached-execution (err u39))
Added an issue: https://github.com/Trust-Machines/stacks-sbtc/issues/590

2023-07-20 09:24 UTC, friedger commented on sbtc-mini/contracts/sbtc-stacking-pool.clar
> +        (ok u3)
Codes should be constants with some meaningful names.

2023-07-20 09:24 UTC, friedger commented on sbtc-mini/contracts/sbtc-stacking-pool.clar
> +            (extend-delegate-response (unwrap! (as-contract (contract-call? .pox-3 delegate-stack-extend stacker pox-burn-address u1)) err-mass-delegate-stack-extend))
Idea for optimization: use `as-contract` around `(fold mass-delegate-stack-extend` To be verified whether it makes a difference.

2023-07-20 09:24 UTC, friedger commented on sbtc-mini/contracts/sbtc-stacking-pool.clar
> +                                    ;; Chore - anything additional in this branch?
We could emit a print event

2023-07-20 09:24 UTC, friedger commented on sbtc-mini/contracts/sbtc-stacking-pool.clar
> +        (asserts!
I find this control flow hard to understand. Suggestion:

```
(if (is-none current-candidate-status) (add-wallet-candiate ....) (update-wallet-candidate...))
(maybe-aggregate-commit...)
```

Can a whale trigger the aggregate commit? If not

```
(if (is-none current-candidate-status) 
   ;; handle new candidate
   (add-wallet-candiate ....) 
   ;; handle existing candidate
   (begin
     (update-wallet-candidate...)
     (maybe-aggregate-commit...)))
```

2023-07-20 10:22 UTC, setzeus commented on sbtc-mini/contracts/sbtc-stacking-pool.clar
> +                                    ;; Chore - anything additional in this branch?
Great idea, doing so.

2023-07-20 10:24 UTC, setzeus commented on sbtc-mini/contracts/sbtc-stacking-pool.clar
> +        (ok u3)
Copy. Err responses are clear to me how to identify with uint, but how/what would you use to identify an (ok ...) response? 

Same thing as error? Just a number saved as more meaningful string constant?

2023-07-20 13:06 UTC, friedger commented on sbtc-mini/contracts/sbtc-stacking-pool.clar
> +        (ok u3)
Yes, like `(ok result-committed)`

2023-07-20 13:48 UTC, friedger commented on sbtc-mini/contracts/sbtc-stacking-pool.clar
> +        (ok u3)
Or better `ok-committed`

2023-07-21 00:41 UTC, MarvinJanssen commented on sbtc-mini/contracts/sbtc-stacking-pool.clar
> +        (ok u3)
Given our design pattern for error constants, I think the latter makes the most sense.

```clarity
(define-constant ok-committed (ok u3))
```

2023-07-21 00:42 UTC, MarvinJanssen commented on sbtc-mini/contracts/sbtc-stacking-pool.clar
> +            (extend-delegate-response (unwrap! (as-contract (contract-call? .pox-3 delegate-stack-extend stacker pox-burn-address u1)) err-mass-delegate-stack-extend))
It should make a difference.

2023-07-21 00:42 UTC, MarvinJanssen commented on sbtc-mini/contracts/sbtc-stacking-pool.clar
> +                                    ;; Chore - anything additional in this branch?
Good idea, we do not have a comprehensive spec for custom events yet. (Something I will bring up later.)

2023-07-21 00:44 UTC, MarvinJanssen commented on sbtc-mini/contracts/sbtc-stacking-pool.clar
> +        (asserts!
Both if branches can be abstracted into two private functions.

2023-07-22 14:35 UTC, setzeus commented on sbtc-mini/contracts/sbtc-stacking-pool.clar
> +        (asserts!
Removed the (if ...) that was previously there in exchange for that series of asserts! Should I change back?

Re: Hoisting Out Private Funcs
Great discussion point here. My personal rule-of-thumb is it's harder to hop around private-functions than it is to read a single well-commented / well-labeled function. 

If I need a series of functions for more than one place, of course I'll hoist out into a private function to no repeat, otherwise though, if it's only callable by one other function I'll leave it as-is. 

Thoughts here? Good opportunity to capture & document in the new docs Marvin introduced.

2023-07-22 14:54 UTC, setzeus commented on sbtc-mini/contracts/sbtc-stacking-pool.clar
> +            (extend-delegate-response (unwrap! (as-contract (contract-call? .pox-3 delegate-stack-extend stacker pox-burn-address u1)) err-mass-delegate-stack-extend))
Wasn't picked up but updated with the (as-contract ...) wrapped around the (fold ...).

2023-07-22 15:06 UTC, friedger commented on sbtc-mini/contracts/sbtc-stacking-pool.clar
> +        (asserts!
I like to read in particular public functions without going into unnecessary details. I think that is also true for the user of a contract.
In a second go I would verify whether the private functions indeed implement what the name suggests.

2023-07-24 05:35 UTC, MarvinJanssen commented on sbtc-mini/contracts/sbtc-stacking-pool.clar
> +        ok-voted
These nested `asserts!` are still a little tricky to follow. It is not immediately clear what these short-circuit branches belong to.

2023-07-24 10:23 UTC, friedger commented on sbtc-mini/contracts/sbtc-stacking-pool.clar
> +            (extend-delegate-response (unwrap! (as-contract (contract-call? .pox-3 delegate-stack-extend stacker pox-burn-address u1)) err-mass-delegate-stack-extend))
The `as-contract` should be removed here. @setzeus

2023-07-24 10:24 UTC, friedger commented on sbtc-mini/contracts/sbtc-stacking-pool.clar
> +        (asserts!
Let's move this discussion to the document or somewhere else and let's move this PR forward.

I suggest to merge this PR and open a new issue for better readability.

2023-07-24 10:25 UTC, friedger requested changes
The last thing I would like to see is the removal of `as-contract` in `mass-delegate-stack-extend` and tests are failing.

2023-07-24 21:38 UTC, friedger commented on sbtc-mini/contracts/sbtc-stacking-pool.clar
> +        ok-voted
We can improve readability in a new PR

2023-07-24 21:39 UTC, friedger commented on sbtc-mini/contracts/sbtc-stacking-pool.clar
> +                                    ;; Chore - anything additional in this branch?
events would be out of scope for this PR

2023-07-24 22:30 UTC, setzeus commented on sbtc-mini/contracts/sbtc-stacking-pool.clar
> +            (extend-delegate-response (unwrap! (as-contract (contract-call? .pox-3 delegate-stack-extend stacker pox-burn-address u1)) err-mass-delegate-stack-extend))
Not picked up but now removed, all conversations should be resolved / ready.

2023-07-25 07:05 UTC, friedger approved these changes
Let's merge this and optimize in a separate PR

2023-07-25 07:06 UTC, friedger commented
@MarvinJanssen Do you have time to review?

2023-07-26 12:24 UTC, FriendsFerdinand commented on sbtc-mini/contracts/sbtc-stacking-pool.clar
> +                    {threshold-wallet-candidates: (unwrap! (as-max-len? (append (get threshold-wallet-candidates next-pool) pox-addr) u100) err-candidates-overflow)}
There's nothing stopping a signer with a low stake in the protocol to fill the entire list with rubbish addresses.

2023-07-26 12:42 UTC, setzeus commented on sbtc-mini/contracts/sbtc-stacking-pool.clar
> +                    {threshold-wallet-candidates: (unwrap! (as-max-len? (append (get threshold-wallet-candidates next-pool) pox-addr) u100) err-candidates-overflow)}
In line 477 I assert that signer hasn't yet voted. 

So I believe that at most one signer with a low stake would be able to submit a single rubbish address? Or am I misunderstanding?

Either way we could / should check against the address by version I believe (though agreed I'll open another issue for that so this can get approved merged).

2023-07-26 13:24 UTC, FriendsFerdinand commented on sbtc-mini/contracts/sbtc-stacking-pool.clar
> +                    ok-vote-existing-candidate-lost)
This is the outcome of the branch where where someone voted correctly, no?
Why are we adding the `-lost` part here? That seems to indicate that you can't vote anymore after someone has lost.

2023-07-26 13:55 UTC, setzeus commented on sbtc-mini/contracts/sbtc-stacking-pool.clar
> +                    ok-vote-existing-candidate-lost)
Idea here is to keep branches returning parallel (ok ...) responses. 

Since a signer is voting for an existing candidate, that vote either pushes the existing candidate over the threshold-consensus, or it doesn't. 

If it does push existing candidate past consensus, we return (ok-vote-existing-candidate-won ...) - which is an ok vote for an existing candidate that won. 

If it doesn't push the existing candidate past consensus, we return (ok-vote-existing-candidate-lost ...) - which is an ok vote for an existing candidate that lost / didn't push the candidate past consensus.

Open to other naming conventions for these responses if you have any particular suggestion in mind.

2023-07-26 14:12 UTC, FriendsFerdinand commented on sbtc-mini/contracts/sbtc-stacking-pool.clar
> +                    ok-vote-existing-candidate-lost)
@setzeus Ok, it should be called `ok-vote-existing-candidate`

2023-07-26 14:27 UTC, FriendsFerdinand commented on sbtc-mini/contracts/sbtc-stacking-pool.clar
> +            (extend-delegate-unlock-burn-height (get unlock-burn-height extend-delegate-response))
Why are we always setting the `pox-addr` to the `pox-burn-address` ? Don't we have to use the `pox-addr` in the parameters?

2023-07-26 14:28 UTC, FriendsFerdinand commented on sbtc-mini/contracts/sbtc-stacking-pool.clar
> +        (asserts! (is-ok pox-return) err-mass-delegate-stack-extend)
We can `unwrap!` instead of doing 2 commands (`asserts!` and `is-ok`)

2023-07-26 16:03 UTC, setzeus commented on sbtc-mini/contracts/sbtc-stacking-pool.clar
> +            (extend-delegate-unlock-burn-height (get unlock-burn-height extend-delegate-response))
Yes. Great catch here, forget to update accordingly. Now outdated in latest commit:

https://github.com/Trust-Machines/stacks-sbtc/pull/578/commits/47e25a3065373ce482534db5410485e808892f93

2023-07-26 16:04 UTC, setzeus commented on sbtc-mini/contracts/sbtc-stacking-pool.clar
> +        (asserts! (is-ok pox-return) err-mass-delegate-stack-extend)
Copy, fixed.

2023-07-26 16:23 UTC, FriendsFerdinand approved these changes

2023-07-26 18:25 UTC, merged

2023-07-27 03:17 UTC, MarvinJanssen commented
Thanks @friedger