Activation state of stacking pool
Trust-Machines/stacks-sbtc pull request #659
Opened 2023-08-04 13:48 UTC by friedger

This PR
* adds a getter for active state
* prevents extending the stacking pool if the locked amount is below 1m STX
* fixes #625

2023-08-07 04:00 UTC, MarvinJanssen requested changes
Looks good. Just need some unit tests for the new state check.

2023-08-07 04:00 UTC, MarvinJanssen commented on sbtc-mini/contracts/sbtc-stacking-pool.clar
> +(define-constant minimal-pool-amount-for-activation u1000000000000)
I wonder if we ever want to change this value. We could make it updatable by protocol call, then a future version could change it if need be.

2023-08-07 08:32 UTC, friedger commented on sbtc-mini/contracts/sbtc-stacking-pool.clar
> +(define-constant minimal-pool-amount-for-activation u1000000000000)
Done

2023-08-07 16:29 UTC, FriendsFerdinand commented
Why are we going back to the `pox-3` for cycle-height related queries?

2023-08-07 22:03 UTC, friedger commented
@FriendsFerdinand What? Where?

2023-08-07 22:33 UTC, friedger commented
@MarvinJanssen Unit tests added

2023-08-08 20:19 UTC, setzeus approved these changes
Have a comment on a possibly-superfluous (match ...) but outside of that pulled, ran clarinet console & can confirm that all unit tests are passing. 

LGTM.

2023-08-08 20:19 UTC, setzeus commented on sbtc-mini/contracts/sbtc-stacking-pool.clar
>  		(match (as-contract (contract-call? .pox-3 stack-aggregation-commit-indexed pox-addr next-cycle))
Is the (match ...) needed since both branches return true?

2023-08-08 21:08 UTC, friedger commented on sbtc-mini/contracts/sbtc-stacking-pool.clar
>  		(match (as-contract (contract-call? .pox-3 stack-aggregation-commit-indexed pox-addr next-cycle))
Is there a different way to ignore the result? We are happy with ok or err

2023-08-08 21:09 UTC, friedger commented on sbtc-mini/contracts/sbtc-stacking-pool.clar
>  		(match (as-contract (contract-call? .pox-3 stack-aggregation-commit-indexed pox-addr next-cycle))
@setzeus ☝️

2023-08-09 10:15 UTC, FriendsFerdinand approved these changes

2023-08-09 10:59 UTC, merged