[sBTC-mini] Unchecked raw-coinbase-tx
Trust-Machines/stacks-sbtc pull request #663
Opened 2023-08-07 05:43 UTC by CAGS295

Small issue I noted. It looks like the parsing checks are missing `raw-coinbase-tx`.

2023-08-07 07:47 UTC, friedger commented
It is not good that the change did not effect the tests. @CAGS295 

Either we should remove the contract call or add a check for the result and compare `parsed-coinbase-tx` with some data

2023-08-07 07:48 UTC, friedger requested changes
Add an assert for `parsed-coinbase-tx`

2023-08-07 16:59 UTC, CAGS295 commented
I agree, `.clarity-bitcoin was-segwit-tx-mined-compact` parses it internally [here](https://github.com/Trust-Machines/stacks-sbtc/blob/main/sbtc-mini/contracts/clarity-bitcoin.clar#L558) anyway. I lean towards removing the call and implementing a separate test for parse-tx instead.

2023-08-09 12:18 UTC, FriendsFerdinand approved these changes

2023-08-09 12:44 UTC, merged