Rename peg-in/peg-out to deposit/withdrawl
Trust-Machines/stacks-sbtc pull request #664
Opened 2023-08-08 09:25 UTC by friedger

This PR
* renames sbtc-peg-in-processor and sbtc-peg-out-processor and corresponding names in clarity code
* renames sbtc-peg-transfer to sbtc-hand-off
* renames peg-wallet to sbtc-wallet
* fixes #654

2023-08-09 11:52 UTC, FriendsFerdinand commented
Typos: withdrawl is spelled withdrawal.

2023-08-09 12:13 UTC, FriendsFerdinand requested changes
Typos: withdrawl should be spelled withdrawal.

2023-08-09 14:54 UTC, setzeus requested changes

2023-08-09 14:54 UTC, setzeus commented on sbtc-mini/Clarinet.toml
> +[contracts.sbtc-withdrawl-processor]
As mentioned by @FriendsFerdinand , only issue I see is that "withdrawl" needs to be universally updated to "withdrawal."

Outside of that, everything else LGTM.

2023-08-09 15:32 UTC, friedger commented on sbtc-mini/Clarinet.toml
> +[contracts.sbtc-withdrawl-processor]
Typo fixed

2023-08-10 08:59 UTC, FriendsFerdinand approved these changes

2023-08-10 12:03 UTC, setzeus approved these changes
Withdrawal spelling issue fixed, all unit tests intact - LGTM!

2023-08-10 12:10 UTC, merged

2023-08-16 03:32 UTC, MarvinJanssen commented
I wish you could have waited with this. Peg out is still in flight and it'll be headaches merging now. 

Anyway, appreciate you proactively taking on this chore.